# Generated by Django 3.1.7 on 2021-06-12 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_beach_advisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id_question', models.IntegerField(primary_key=True, serialize=False)),
                ('txtquestion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id_answer', models.AutoField(primary_key=True, serialize=False)),
                ('txtanswer', models.CharField(max_length=255)),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red_beach_advisors.questions')),
            ],
        ),
    ]
