# Generated by Django 3.1.7 on 2021-06-12 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red_beach_advisors', '0002_answers_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='email_register',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
