# Generated by Django 3.1.7 on 2021-08-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red_beach_advisors', '0003_answers_email_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id_city', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('id_estate', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('division', models.CharField(max_length=255)),
                ('cost_living', models.FloatField()),
                ('density', models.FloatField()),
                ('gross_rent', models.FloatField()),
                ('health_care', models.IntegerField()),
                ('population', models.IntegerField()),
                ('urban', models.FloatField()),
                ('rural', models.FloatField()),
                ('price_hou', models.IntegerField()),
                ('sector_1', models.TextField()),
                ('sector_2', models.TextField()),
                ('sector_3', models.TextField()),
                ('sector_4', models.TextField()),
                ('sector_5', models.TextField()),
                ('sector_6', models.TextField()),
                ('sector_7', models.TextField()),
                ('cluster1', models.IntegerField()),
                ('cluster2', models.IntegerField()),
            ],
        ),
    ]
